name: Build and Deploy

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    #- name: Install dependencies
      #run: npm ci

    #- name: Build
      #run: npm run build

    - name: Install cloudflared
      run: |
        wget -q https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64.deb
        sudo dpkg -i cloudflared-linux-amd64.deb

    - name: Setup SSH key
      run: |
        mkdir -p ~/.ssh/ && touch ~/.ssh/known_hosts
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/webflix_deploy_key
        chmod 600 ~/.ssh/webflix_deploy_key
        eval "$(ssh-agent -s)" # Start the SSH agent

    - name: Add SSH Host Key
      run: |
        echo "${{ secrets.SSH_PUBLIC_KEY }}" >> ~/.ssh/known_hosts

    - name: Configure SSH for cloudflared
      run: |
        echo "
        Host myhost
          HostName ${{ secrets.SSH_HOST }}
          User ${{ secrets.SSH_USERNAME }}
          PubkeyAuthentication yes
          ProxyCommand cloudflared access ssh --hostname %h
          IdentityFile ~/.ssh/webflix_deploy_key
        " >> ~/.ssh/config

    - name: Deploy to homeserver
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      env:
        DEPLOY_PATH: ${{ secrets.SERVER_DEPLOY_PATH }}
      run: |
        ssh -i ~/.ssh/webflix_deploy_key -o UserKnownHostsFile=~/.ssh/known_hosts myhost "
          cd $DEPLOY_PATH
          git pull
          npm ci
          npm run build
          export PATH=\$PATH:~/.nvm/versions/node/v22.13.1/bin
          pm2 restart webflix-streamer
        "
